In [1]:
ls

ClimateChange.xlsx  Untitled.ipynb      未命名.ipynb        未命名1.ipynb

In [2]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [6]:
df = pd.read_excel('ClimateChange.xlsx',sheet_name=['Data','Country','Series'])

In [111]:
df_c = df['Country']
df_d = df['Data']

In [113]:
df_c.set_index('Income group')

TypeError: 'Series' object is not callable

In [114]:
type(df_c)

pandas.core.frame.DataFrame

In [62]:
df_d

      Country code                    Country name ...          2010 2011
0              ABW                           Aruba ...            ..   ..
1              ADO                         Andorra ...            ..   ..
2              AFG                     Afghanistan ...            ..   ..
3              AGO                          Angola ...            ..   ..
4              ALB                         Albania ...            ..   ..
5              ARE            United Arab Emirates ...            ..   ..
6              ARG                       Argentina ...            ..   ..
7              ARM                         Armenia ...            ..   ..
8              ASM                  American Samoa ...            ..   ..
9              ATG             Antigua and Barbuda ...            ..   ..
10             AUS                       Australia ...            ..   ..
11             AUT                         Austria ...            ..   ..
12             AZE                      Azerbaijan ...            ..   ..
13             BDI                         Burundi ...            ..   ..
14             BEL                         Belgium ...            ..   ..
15             BEN                           Benin ...            ..   ..
16             BFA                    Burkina Faso ...            ..   ..
17             BGD                      Bangladesh ...            ..   ..
18             BGR                        Bulgaria ...            ..   ..
19             BHR                         Bahrain ...            ..   ..
20             BHS                    Bahamas, The ...            ..   ..
21             BIH          Bosnia and Herzegovina ...            ..   ..
22             BLR                         Belarus ...            ..   ..
23             BLZ                          Belize ...            ..   ..
24             BMU                         Bermuda ...            ..   ..
25             BOL                         Bolivia ...            ..   ..
26             BRA                          Brazil ...            ..   ..
27             BRB                        Barbados ...            ..   ..
28             BRN               Brunei Darussalam ...            ..   ..
29             BTN                          Bhutan ...            ..   ..
...            ...                             ... ...           ...  ...
12614          TCA        Turks and Caicos Islands ...            ..   ..
12615          TCD                            Chad ...   3.09871e+06   ..
12616          TGO                            Togo ...   2.61606e+06   ..
12617          THA                        Thailand ...   2.35016e+07   ..
12618          TJK                      Tajikistan ...   1.82284e+06   ..
12619          TKM                    Turkmenistan ...   2.49579e+06   ..
12620          TMP                     Timor-Leste ...        315944   ..
12621          TON                           Tonga ...       26326.7   ..
12622          TTO             Trinidad and Tobago ...        186464   ..
12623          TUN                         Tunisia ...   7.09954e+06   ..
12624          TUR                          Turkey ...   5.06356e+07   ..
12625          TUV                          Tuvalu ...            ..   ..
12626          TZA                        Tanzania ...   1.18381e+07   ..
12627          UGA                          Uganda ...   4.44548e+06   ..
12628          UKR                         Ukraine ...   3.12379e+07   ..
12629          URY                         Uruguay ...   3.10484e+06   ..
12630          USA                   United States ...   2.54349e+08   ..
12631          UZB                      Uzbekistan ...   1.03912e+07   ..
12632          VCT  St. Vincent and the Grenadines ...       52261.2   ..
12633          VEN                   Venezuela, RB ...      27103960   ..
12634          VIR           Virgin Islands (U.S.) ...        104616   ..
12635          VNM                         Vietnam ...   2.50377e+07   ..
12636          VUT                         Vanuatu ...       61350.7   ..
12637          WBG              West Bank and Gaza ...   2.99367e+06   ..
12638          WSM                           Samoa ...         42841   ..
12639          YEM                     Yemen, Rep. ...    7.6487e+06   ..
12640          ZAF                    South Africa ...   3.08446e+07   ..
12641          ZAR                Congo, Dem. Rep. ...     2.322e+07   ..
12642          ZMB                          Zambia ...   4.61473e+06   ..
12643          ZWE                        Zimbabwe ...   4.81487e+06   ..

[12644 rows x 28 columns]

In [63]:
 df_d = df_d.fillna(method='ffill',axis=1).fillna(method='bfill',axis=1)
df_d_gb=df_d[df_d['Series code']=='EN.ATM.CO2E.KT'].dropna(axis=1,how='all')

In [64]:
pd.concat([df_d_gb,df_c_gb],columns=[])

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"