In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
df_data = pd.read_excel("ClimateChange.xlsx", sheetname='Data')

In [5]:
df_co2 = df_data[df_data['Series code'] ==
                     'EN.ATM.CO2E.KT'].set_index('Country code')
df_gdp = df_data[df_data['Series code'] ==
                     'NY.GDP.MKTP.CD'].set_index('Country code')

In [12]:
df_co2.head()

,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,1994,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
Country code,,,,,,,,,,,,,,,,,,,,,
ABW,Aruba,EN.ATM.CO2E.KT,"CO2 emissions, total (KtCO2)",0,1,1840.83,1928.84,1723.49,1771.16,1763.83,...,2255.2,2255.2,2258.87,2273.54,2273.54,2357.88,2288.21,..,..,..
ADO,Andorra,EN.ATM.CO2E.KT,"CO2 emissions, total (KtCO2)",0,1,..,..,..,..,..,...,531.715,535.382,564.718,575.719,546.383,539.049,539.049,..,..,..
AFG,Afghanistan,EN.ATM.CO2E.KT,"CO2 emissions, total (KtCO2)",0,1,2676.91,2493.56,1426.46,1375.12,1320.12,...,359.366,583.053,704.064,700.397,696.73,715.065,814.074,..,..,..
AGO,Angola,EN.ATM.CO2E.KT,"CO2 emissions, total (KtCO2)",0,1,4429.74,4367.4,4418.73,5801.19,3890.69,...,12665.8,9064.82,18793.4,19156.4,22266,25152,24370.9,..,..,..
ALB,Albania,EN.ATM.CO2E.KT,"CO2 emissions, total (KtCO2)",0,1,7488.01,3971.36,2387.22,2343.21,1928.84,...,3751.34,4290.39,4004.36,4602.09,4231.72,4481.07,4176.71,..,..,..

In [6]:
df_co2_nan = df_co2.replace({'..': pd.np.NaN})
df_gdp_nan = df_gdp.replace({'..': pd.np.NaN})

In [17]:
df_co2_nan.head()

,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,1994,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
Country code,,,,,,,,,,,,,,,,,,,,,
ABW,Aruba,EN.ATM.CO2E.KT,"CO2 emissions, total (KtCO2)",0,1,1840.834,1928.842,1723.490,1771.161,1763.827,...,2255.205,2255.205,2258.872,2273.540,2273.540,2357.881,2288.208,NaN,NaN,NaN
ADO,Andorra,EN.ATM.CO2E.KT,"CO2 emissions, total (KtCO2)",0,1,NaN,NaN,NaN,NaN,NaN,...,531.715,535.382,564.718,575.719,546.383,539.049,539.049,NaN,NaN,NaN
AFG,Afghanistan,EN.ATM.CO2E.KT,"CO2 emissions, total (KtCO2)",0,1,2676.910,2493.560,1426.463,1375.125,1320.120,...,359.366,583.053,704.064,700.397,696.730,715.065,814.074,NaN,NaN,NaN
AGO,Angola,EN.ATM.CO2E.KT,"CO2 emissions, total (KtCO2)",0,1,4429.736,4367.397,4418.735,5801.194,3890.687,...,12665.818,9064.824,18793.375,19156.408,22266.024,25151.953,24370.882,NaN,NaN,NaN
ALB,Albania,EN.ATM.CO2E.KT,"CO2 emissions, total (KtCO2)",0,1,7488.014,3971.361,2387.217,2343.213,1928.842,...,3751.341,4290.390,4004.364,4602.085,4231.718,4481.074,4176.713,NaN,NaN,NaN

In [15]:
df_co2_nan.iloc[:, 5:]

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
Country code,,,,,,,,,,,,,,,,,,,,,
ABW,1840.834,1928.842,1723.490,1771.161,1763.827,1785.829,1811.498,1851.835,1668.485,1686.820,...,2255.205,2255.205,2258.872,2273.540,2273.540,2357.881,2288.208,NaN,NaN,NaN
ADO,NaN,NaN,NaN,NaN,NaN,407.037,425.372,458.375,484.044,513.380,...,531.715,535.382,564.718,575.719,546.383,539.049,539.049,NaN,NaN,NaN
AFG,2676.910,2493.560,1426.463,1375.125,1320.120,1268.782,1199.109,1114.768,1056.096,832.409,...,359.366,583.053,704.064,700.397,696.730,715.065,814.074,NaN,NaN,NaN
AGO,4429.736,4367.397,4418.735,5801.194,3890.687,11012.001,10491.287,7381.671,7308.331,9156.499,...,12665.818,9064.824,18793.375,19156.408,22266.024,25151.953,24370.882,NaN,NaN,NaN
ALB,7488.014,3971.361,2387.217,2343.213,1928.842,2086.523,2016.850,1543.807,1752.826,2992.272,...,3751.341,4290.390,4004.364,4602.085,4231.718,4481.074,4176.713,NaN,NaN,NaN
ARE,52009.061,57010.849,58136.618,65980.331,73130.981,70641.088,41059.399,41646.119,81495.408,78374.791,...,84300.663,106365.002,112877.594,115627.844,122752.825,137981.876,155066.429,NaN,NaN,NaN
ARG,112613.570,117021.304,121447.373,118609.115,123350.546,122547.473,129217.746,134677.909,137673.848,145488.225,...,131406.945,142349.273,155000.423,158924.113,175528.289,183727.701,192378.154,NaN,NaN,NaN
ARM,NaN,NaN,3681.668,2929.933,2966.603,3490.984,2607.237,3278.298,3406.643,3058.278,...,3003.273,3428.645,3644.998,4349.062,4378.398,5056.793,5548.171,NaN,NaN,NaN
ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ATG,300.694,293.360,293.360,308.028,311.695,322.696,322.696,337.364,333.697,348.365,...,363.033,388.702,407.037,410.704,425.372,436.373,447.374,NaN,NaN,NaN
AUS,287331.452,281530.258,294456.433,302116.796,303957.630,307433.946,329259.930,333623.660,346912.868,325523.257,...,341397.700,346476.495,349223.078,367393.063,377381.971,380814.283,399218.956,NaN,NaN,NaN
AUT,60960.208,65888.656,60531.169,58213.625,57586.568,60622.844,61055.550,61359.911,63549.110,61755.947,...,65118.586,72316.907,72118.889,74385.095,72126.223,68807.588,67725.823,NaN,NaN,NaN
AZE,NaN,NaN,44172.682,43285.268,42383.186,33586.053,31565.536,29966.724,31594.872,29299.330,...,30007.061,31162.166,32262.266,34491.802,39317.574,42236.506,47139.285,NaN,NaN,NaN
BDI,304.361,344.698,319.029,337.364,341.031,333.697,330.030,315.362,300.694,293.360,...,220.020,165.015,161.348,165.015,198.018,183.350,179.683,NaN,NaN,NaN
BEL,108469.860,117578.688,114373.730,108924.568,113306.633,112976.603,119624.874,116295.238,119184.834,115844.197,...,107531.108,114835.772,111282.449,107116.737,106816.043,102529.320,104879.867,NaN,NaN,NaN
BEN,715.065,828.742,905.749,1133.103,1265.115,1327.454,1265.115,1217.444,1213.777,1562.142,...,2053.520,2321.211,2398.218,2566.900,3729.339,3879.686,4066.703,NaN,NaN,NaN
BFA,586.720,627.057,630.724,627.057,645.392,627.057,707.731,806.740,861.745,931.418,...,1004.758,1078.098,1103.767,1125.769,1360.457,1646.483,1855.502,NaN,NaN,NaN
BGD,15533.412,15940.449,17748.280,17407.249,18969.391,22816.074,24029.851,25063.945,24040.852,25232.627,...,33699.730,33824.408,39735.612,37652.756,46644.240,46930.266,46526.896,NaN,NaN,NaN
BGR,77729.399,59706.094,53600.539,69328.302,55848.410,59805.103,56691.820,53681.213,50993.302,43981.998,...,44634.724,47307.967,46787.253,47909.355,48943.449,52812.134,50538.594,NaN,NaN,NaN
BHR,11884.747,11503.379,10590.296,15141.043,15254.720,16021.123,15621.420,17319.241,18404.673,18019.638,...,15698.427,16468.497,17275.237,18595.357,20186.835,21481.286,22478.710,NaN,NaN,NaN
BHS,1950.844,1782.162,1793.163,1716.156,1719.823,1730.824,1730.824,1741.825,1793.163,1796.830,...,2082.856,1870.170,2009.516,2108.525,2137.861,2148.862,2156.196,NaN,NaN,NaN
BIH,NaN,NaN,3938.358,3270.964,3630.330,3542.322,5368.488,12500.803,16226.475,18771.373,...,22944.419,23263.448,24634.906,25632.330,27469.497,28987.635,31275.843,NaN,NaN,NaN
BLR,NaN,NaN,87487.286,74451.101,65914.325,62118.980,60157.135,59519.077,57597.569,55819.074,...,52390.429,53721.550,58220.959,59042.367,61807.285,60256.144,62815.710,NaN,NaN,NaN
BLZ,311.695,359.366,355.699,377.701,374.034,377.701,308.028,388.702,370.367,601.388,...,359.366,374.034,381.368,396.036,407.037,425.372,425.372,NaN,NaN,NaN
BMU,597.721,509.713,407.037,480.377,473.043,465.709,476.710,476.710,462.042,495.045,...,524.381,509.713,671.061,443.707,520.714,517.047,388.702,NaN,NaN,NaN
BOL,5504.167,5779.192,6648.271,8038.064,8907.143,9424.190,8734.794,9842.228,10326.272,9768.888,...,8346.092,11521.714,10626.966,10293.269,10465.618,13054.520,12834.500,NaN,NaN,NaN
BRA,208886.988,219330.604,220705.729,230738.641,242154.012,275564.049,301244.050,321199.864,314012.544,322068.943,...,335185.802,324753.187,341166.679,349967.479,352541.713,368368.485,393219.744,NaN,NaN,NaN
BRB,1074.431,1206.443,979.089,1114.768,748.068,828.742,850.744,902.082,1140.437,1210.110,...,1228.445,1268.782,1294.451,1353.123,1371.458,1349.456,1353.123,NaN,NaN,NaN
BRN,6420.917,5815.862,5808.528,5588.508,5408.825,5515.168,5595.842,5812.195,5984.544,4598.418,...,5320.817,5357.487,5361.154,5126.466,4822.105,9559.869,10593.963,NaN,NaN,NaN
BTN,128.345,187.017,216.353,187.017,212.686,249.356,304.361,396.036,385.035,385.035,...,513.380,465.709,469.376,682.062,421.705,579.386,733.400,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCA,NaN,NaN,NaN,NaN,NaN,11.001,11.001,11.001,14.668,14.668,...,99.009,102.676,102.676,121.011,143.013,157.681,157.681,NaN,NaN,NaN
TCD,146.680,69.673,88.008,99.009,102.676,102.676,106.343,113.677,113.677,121.011,...,168.682,381.368,377.701,399.703,407.037,462.042,495.045,NaN,NaN,NaN
TGO,773.737,843.410,836.076,865.412,832.409,953.420,1059.763,986.423,1166.106,1536.473,...,1232.112,1463.133,1397.127,1338.455,1221.111,1316.453,1419.129,NaN,NaN,NaN
THA,95833.378,116148.558,126830.529,142554.625,158278.721,181461.495,202711.760,210064.095,186503.620,196947.236,...,230635.965,245674.332,267760.673,275164.346,283987.148,282091.309,285732.640,NaN,NaN,NaN
TJK,NaN,NaN,7220.323,5170.470,2354.214,2449.556,2827.257,2152.529,2497.227,2519.229,...,1881.171,2075.522,2233.203,2291.875,2420.220,3245.295,3146.286,NaN,NaN,NaN
TKM,NaN,NaN,28067.218,27663.848,33476.043,34620.147,31363.851,29930.054,26046.701,35115.192,...,41074.067,43160.590,39640.270,41759.796,43871.988,45866.836,47839.682,NaN,NaN,NaN
TMP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,161.348,161.348,176.016,176.016,179.683,183.350,190.684,NaN,NaN,NaN
TON,77.007,91.675,88.008,102.676,106.343,110.010,110.010,113.677,110.010,128.345,...,143.013,176.016,172.349,172.349,172.349,176.016,176.016,NaN,NaN,NaN
TTO,16959.875,21048.580,20986.241,16820.529,19853.138,20967.906,21781.980,19229.748,19317.756,22816.074,...,26890.111,27696.851,31554.535,30949.480,34480.801,37036.700,49772.191,NaN,NaN,NaN
TUN,13267.206,15489.408,15023.699,16501.500,15940.449,15735.097,16758.190,16945.207,18001.303,18331.333,...,21015.577,21396.945,22445.707,22801.406,23127.769,23868.503,25012.607,NaN,NaN,NaN
TUR,150790.707,151799.132,154494.377,164259.598,161659.695,176705.396,192499.165,202887.776,205421.673,196767.553,...,205678.363,218509.196,225406.823,237368.577,261570.777,284658.209,283979.814,NaN,NaN,NaN
TUV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TZA,2372.549,2434.888,2361.548,2636.573,2445.889,3553.323,3461.648,2882.262,2555.899,2537.564,...,3589.993,3806.346,4352.729,5086.129,5379.489,6039.549,6464.921,NaN,NaN,NaN
UGA,817.741,850.744,861.745,821.408,744.401,957.087,1052.429,1133.103,1338.455,1393.460,...,1705.155,1719.823,1833.500,2339.546,2706.246,3204.958,3747.674,NaN,NaN,NaN
UKR,NaN,NaN,641680.996,546111.642,447010.967,445943.870,412335.815,341196.015,328636.540,332549.229,...,318684.302,352259.354,343121.190,339028.818,327796.797,328856.560,323532.076,NaN,NaN,NaN
URY,3993.363,4554.414,5170.470,4466.406,4066.703,4591.084,5441.828,5555.505,5687.517,6725.278,...,4620.420,4598.418,5610.510,5775.525,6648.271,5999.212,8327.757,NaN,NaN,NaN
USA,4879376.206,4870238.042,4876006.233,5167485.062,5227176.488,5237968.469,5343512.063,5501365.412,5449077.659,5528149.180,...,5437816.302,5471754.387,5563799.754,5595357.956,5514775.631,5581537.033,5461013.744,NaN,NaN,NaN
UZB,NaN,NaN,114014.364,118532.108,110981.755,100912.173,103189.380,101781.252,117571.354,117421.007,...,126914.870,122683.152,119272.842,109599.296,115345.485,115840.530,124905.354,NaN,NaN,NaN
VCT,80.674,77.007,84.341,102.676,121.011,132.012,135.679,135.679,165.015,168.682,...,187.017,194.351,194.351,198.018,201.685,201.685,201.685,NaN,NaN,NaN
VEN,122162.438,115440.827,105873.624,124355.304,129947.479,133236.778,122752.825,133962.844,167321.543,172616.691,...,193261.901,192103.129,168278.630,159584.173,153595.962,163555.534,169532.744,NaN,NaN,NaN
VIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VNM,21407.946,21451.950,22387.035,22970.088,26303.391,29247.992,34378.125,45283.783,47781.010,48026.699,...,71348.819,79438.221,101678.576,104084.128,83735.945,112290.874,127384.246,NaN,NaN,NaN
VUT,69.673,66.006,66.006,66.006,66.006,66.006,84.341,88.008,84.341,84.341,...,84.341,88.008,88.008,55.005,47.671,80.674,91.675,NaN,NaN,NaN
WBG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,414.371,608.722,660.060,...,1166.106,1279.783,1866.503,2742.916,2266.206,2324.878,2053.520,NaN,NaN,NaN
WSM,124.678,124.678,128.345,128.345,121.011,132.012,132.012,132.012,132.012,139.346,...,143.013,150.347,154.014,157.681,157.681,161.348,161.348,NaN,NaN,NaN
YEM,-2999.606,10109.919,14381.974,9431.524,11367.700,11250.356,14935.691,15474.740,12200.109,13894.263,...,15764.433,17304.573,18881.383,20043.822,20791.890,21976.331,23384.459,NaN,NaN,NaN
ZAF,333513.650,346337.149,324852.196,342549.138,358929.627,353458.463,358639.934,371327.754,372218.835,371034.394,...,347686.605,380810.616,414165.648,408199.439,405709.546,433358.726,435877.955,NaN,NaN,NaN
ZAR,4070.370,3755.008,3619.329,3410.310,2478.892,2966.603,3248.962,2926.266,2533.897,2247.871,...,1543.807,1697.821,2280.874,2368.882,2460.557,2552.232,2816.256,NaN,NaN,NaN
ZMB,2445.889,2416.553,2456.890,2500.894,2420.220,2170.864,1870.170,2390.884,2313.877,1807.831,...,1969.179,2101.191,2108.525,2258.872,2284.541,1719.823,1888.505,NaN,NaN,NaN
ZWE,15504.076,15823.105,16901.203,16208.140,17645.604,15130.042,14994.363,14407.643,14253.629,15834.106,...,11932.418,10626.966,9926.569,10773.646,10344.607,9618.541,9075.825,NaN,NaN,NaN

In [18]:
df_co2_fill = df_co2_nan.iloc[:, 5:].fillna(
        method='ffill', axis=1).fillna(method='bfill', axis=1)
df_gdp_fill = df_gdp_nan.iloc[:, 5:].fillna(
        method='ffill', axis=1).fillna(method='bfill', axis=1)

In [19]:
df_co2_fill.loc['CHN']

1990    2460744.017
1991    2584538.270
1992    2695982.067
1993    2878694.009
1994    3058241.330
1995    3320285.150
1996    3463089.131
1997    3469510.048
1998    3324344.519
1999    3318055.614
2000    3405179.867
2001    3487566.356
2002    3694242.143
2003    4525177.009
2004    5288166.032
2005    5790016.984
2006    6414463.080
2007    6791804.714
2008    7031916.207
2009    7031916.207
2010    7031916.207
2011    7031916.207
Name: CHN, dtype: float64

In [8]:
df_co2_fill['CO2-SUM'] = df_co2_fill.sum(axis=1)
df_gdp_fill['GDP-SUM'] = df_gdp_fill.sum(axis=1)

In [11]:
df_co2_fill['CO2-SUM']

Country code
ABW    4.512977e+04
ADO    1.082132e+04
AFG    2.320478e+04
AGO    2.921132e+05
ALB    7.683832e+04
ARE    2.133552e+06
ARG    3.260645e+06
ARM    8.584447e+04
ASM    0.000000e+00
ATG    8.082068e+03
AUS    7.526173e+06
AUT    1.432726e+06
AZE    8.322183e+05
BDI    5.548171e+03
BEL    2.446688e+06
BEN    4.800470e+04
BFA    2.383183e+04
BGD    6.916915e+05
BGR    1.161900e+06
BHR    3.819511e+05
BHS    4.233185e+04
BIH    3.971361e+05
BLR    1.400805e+06
BLZ    9.270176e+03
BMU    1.057563e+04
BOL    2.169691e+05
BRA    6.970787e+06
BRB    2.574234e+04
BRN    1.471970e+05
BTN    9.530533e+03
           ...
TCA    1.503470e+03
TCD    5.588508e+03
TGO    2.601737e+04
THA    4.764214e+06
TJK    7.289263e+04
TKM    8.244773e+05
TMP    3.736673e+03
TON    3.014274e+03
TTO    6.370166e+05
TUN    4.374401e+05
TUR    4.737082e+06
TUV    0.000000e+00
TZA    8.713525e+04
UGA    4.163512e+04
UKR    8.725128e+06
URY    1.272119e+05
USA    1.179918e+08
UZB    2.563699e+06
VCT    3.523987e+03
VEN    3.361121e+06
VIR    0.000000e+00
VNM    1.496565e+06
VUT    1.716156e+03
WBG    2.659675e+04
WSM    3.146286e+03
YEM    3.492377e+05
ZAF    8.397657e+06
ZAR    5.863900e+04
ZMB    4.651589e+04
ZWE    2.826780e+05
Name: CO2-SUM, Length: 218, dtype: float64

In [9]:
df_merge = pd.concat(
        [df_co2_fill['CO2-SUM'], df_gdp_fill['GDP-SUM']], axis=1)

In [10]:
df_merge

                   CO2-SUM       GDP-SUM
Country code
ABW           4.512977e+04  3.552179e+10
ADO           1.082132e+04  4.295724e+10
AFG           2.320478e+04  1.156549e+11
AGO           2.921132e+05  5.983478e+11
ALB           7.683832e+04  1.231033e+11
ARE           2.133552e+06  2.285588e+12
ARG           3.260645e+06  5.426435e+12
ARM           8.584447e+04  8.857234e+10
ASM           0.000000e+00  0.000000e+00
ATG           8.082068e+03  1.607584e+10
AUS           7.526173e+06  1.201386e+13
AUT           1.432726e+06  5.696021e+12
AZE           8.322183e+05  3.410595e+11
BDI           5.548171e+03  2.146471e+10
BEL           2.446688e+06  6.958691e+12
BEN           4.800470e+04  7.624104e+10
BFA           2.383183e+04  9.582299e+10
BGD           6.916915e+05  1.180259e+12
BGR           1.161900e+06  5.096239e+11
BHR           3.819511e+05  2.323205e+11
BHS           4.233185e+04  1.159872e+11
BIH           3.971361e+05  1.672679e+11
BLR           1.400805e+06  5.661979e+11
BLZ           9.270176e+03  1.971244e+10
BMU           1.057563e+04  8.173886e+10
BOL           2.169691e+05  2.154001e+11
BRA           6.970787e+06  1.983363e+13
BRB           2.574234e+04  5.560617e+10
BRN           1.471970e+05  1.550123e+11
BTN           9.530533e+03  1.409816e+10
...                    ...           ...
TCA           1.503470e+03  0.000000e+00
TCD           5.588508e+03  7.704292e+10
TGO           2.601737e+04  4.199836e+10
THA           4.764214e+06  3.773214e+12
TJK           7.289263e+04  5.274599e+10
TKM           8.244773e+05  1.601435e+11
TMP           3.736673e+03  8.200915e+09
TON           3.014274e+03  4.962968e+09
TTO           6.370166e+05  2.489256e+11
TUN           4.374401e+05  5.503293e+11
TUR           4.737082e+06  7.698492e+12
TUV           0.000000e+00  3.863472e+08
TZA           8.713525e+04  2.504186e+11
UGA           4.163512e+04  1.762334e+11
UKR           8.725128e+06  1.704182e+12
URY           1.272119e+05  4.661453e+11
USA           1.179918e+08  2.239484e+14
UZB           2.563699e+06  3.895865e+11
VCT           3.523987e+03  8.274050e+09
VEN           3.361121e+06  3.187683e+12
VIR           0.000000e+00  4.293080e+10
VNM           1.496565e+06  9.468249e+11
VUT           1.716156e+03  7.847088e+09
WBG           2.659675e+04  7.767905e+10
WSM           3.146286e+03  6.780470e+09
YEM           3.492377e+05  2.722866e+11
ZAF           8.397657e+06  4.169526e+12
ZAR           5.863900e+04  1.731822e+11
ZMB           4.651589e+04  1.431524e+11
ZWE           2.826780e+05  1.469907e+11

[218 rows x 2 columns]